### ISSUE TITLE
[BUG]批量处理的图片会出现部分不完整情况

### ISSUE THREAD

**Issue by sailing178** [X-Lucifer/AI-Lossless-Zoomer#1]
![image](https://user-images.githubusercontent.com/89731041/135723762-5dc38970-fd2a-4fd7-b5a7-1db9b4f5f1dd.png)

**Comment by X-Lucifer** [comment]
我这边没有出现不完整的情况, 另外, 动漫图片, 请选择`realesrgan-x4plus-anime`引擎模块, 针对动漫图片做了优化. 去`选项`>`引擎模块` 选择`realesrgan-x4plus-anime`模块即可.
以下是对比效果.

原图: 
![1](https://user-images.githubusercontent.com/11420730/135727422-8c816498-616a-40aa-a0ba-626c44f66c33.jpg)

默认引擎模块: (`realesrgan-x4plus`)
![2](https://user-images.githubusercontent.com/11420730/135727424-926bcd8c-85eb-40f3-b0bf-35ebf955374c.jpg)

动漫图片优化模块: (`realesrgan-x4plus-anime`)
![3](https://user-images.githubusercontent.com/11420730/135727414-431b11b9-4718-4fb6-a1cb-95b126f37e35.jpg)

**Comment by sailing178** [comment]
收到
