### ISSUE TITLE
Windows7运行提示丢失vulkan-1.dll

### ISSUE THREAD

**Issue by xiaxi626** [X-Lucifer/AI-Lossless-Zoomer#20]
运行程序跳出弹窗“无法启动此程序，因为计算机中丢失 vulkan-1.dll。尝试重新安装该程序以解决此问题”。

**Comment by zhj200015** [comment]
下载vulkan-1.dll放入C:\Windows\System32位置即可。

**Comment by X-Lucifer** [comment]
https://github.com/X-Lucifer/AI-Lossless-Zoomer/wiki
