### ISSUE TITLE
zip x64 下载之后运行LosslessZoom.exe，提示从服务器返回了一个参照

### ISSUE THREAD

**Issue by Charltsing** [X-Lucifer/AI-Lossless-Zoomer#25]
zip x64 下载之后运行LosslessZoom.exe，提示从服务器返回了一个参照，这是缺什么依赖还是需要啥硬件？

win10 22h2 x64 最新版

![142505124688E69D7DFAFDB6157A0254](https://github.com/X-Lucifer/AI-Lossless-Zoomer/assets/19963715/a04069e7-5888-4c0a-9911-f86a4c5274b4)

**Comment by xiaohanlaila** [comment]
也遇到一样的问题

**Comment by X-Lucifer** [comment]
找到LosslessZoom.exe文件, 文件属性中打开`兼容性`, 勾选`以管理员身份运行`.
![image](https://github.com/X-Lucifer/AI-Lossless-Zoomer/assets/11420730/614a5de8-a7fc-4b8a-8c8d-39e2eee63018)

**Comment by Charltsing** [comment]
> 找到LosslessZoom.exe文件, 文件属性中打开`兼容性`, 勾选`以管理员身份运行`. 

你可以配置程序以管理员运行啊，或者捕获错误给一个提示，这样搞得很多人不知所措。
