### ISSUE TITLE
以管理员运行，提示参数无效。刚下载的一小时之前的版本

### ISSUE THREAD

**Issue by Charltsing** [X-Lucifer/AI-Lossless-Zoomer#26]
![捕获](https://github.com/X-Lucifer/AI-Lossless-Zoomer/assets/19963715/018fbd1c-f0cc-493e-a6fd-03aaaf83f509)
[error.zip](https://github.com/X-Lucifer/AI-Lossless-Zoomer/files/15375338/error.zip)

第一次启动闪退。
第二次启动提示错误，具体看动画，Windows10 22H2

**Comment by Charltsing** [comment]
这是另一台电脑

![8AE9F2D24ED12E8CAF2B44173FBCC40F](https://github.com/X-Lucifer/AI-Lossless-Zoomer/assets/19963715/4fc44c0e-5ffe-418f-8b3d-a9f1bdd17c09)

**Comment by bluezsd** [comment]
我也提示这个错误，安装2.1版本，再把3.0的模型替换进去，目前正常

**Comment by X-Lucifer** [comment]
最新版本已修复.
