### ISSUE TITLE
3.0版本能不能也出个安装版？绿色版容易出错

### ISSUE THREAD

**Issue by bluezsd** [X-Lucifer/AI-Lossless-Zoomer#29]
3.0版本能不能也出个安装版？绿色版老是提示参数无效

**Comment by ggkan** [comment]
提示返回一个参数，打不开，请问怎么解决？

**Comment by goeway** [comment]
![image](https://github.com/X-Lucifer/AI-Lossless-Zoomer/assets/23276757/fe856527-e8d0-4404-936b-04360dd12b7c)
这是怎么回事呢

**Comment by X-Lucifer** [comment]
以管理员身份运行，参照最新版本.
