### ISSUE TITLE
运行提示vulkan-1.dll丢失。。。（自己解决了）

### ISSUE THREAD

**Issue by drw2005** [X-Lucifer/AI-Lossless-Zoomer#3]
![QQ截图20211008084209](https://user-images.githubusercontent.com/33473981/136481041-7521a766-5e9b-4221-8cdd-205bd2ecbae5.png)

从网上下载vulkan-1.dll放到syswow64里，但是好像无法注册，提示下面的错误：
![QQ截图20211008082837](https://user-images.githubusercontent.com/33473981/136481880-ef9c9a5f-8076-4b46-bf07-fc291bac4f70.png)

请教大神有没有解决办法？

**Comment by xiejianwei01** [comment]
vulkan-1.dll 怎么解决的？
