### ISSUE TITLE
刚进入显示无法读写文件的错误，请问怎么办？会有影响吗？

### ISSUE THREAD

**Issue by bulabulalaen** [X-Lucifer/AI-Lossless-Zoomer#4]
![image](https://user-images.githubusercontent.com/53595830/136727135-7039d182-3440-4ce6-b3ae-fd962783a067.png)

**Comment by X-Lucifer** [comment]
找到软件, 右键属性设置这里, 把"使用管理员身份运行"勾选上. 或者每次运行软件, 选择以管理员身份运行.
![屏幕截图 2021-10-11 200943](https://user-images.githubusercontent.com/11420730/136787851-a537dbb3-b53b-43fb-9cd3-e4b3bc1805bf.png)

**Comment by bulabulalaen** [comment]
> 找到软件, 右键属性设置这里, 把"使用管理员身份运行"勾选上. 或者每次运行软件, 选择以管理员身份运行. ![屏幕截图 2021-10-11 200943](https://user-images.githubusercontent.com/11420730/136787851-a537dbb3-b53b-43fb-9cd3-e4b3bc1805bf.png)

ok，谢谢！
