### ISSUE TITLE
希望添加两个功能~ 会易于快速调用

### ISSUE THREAD

**Issue by Karanoyo** [X-Lucifer/AI-Lossless-Zoomer#9]
●右键图片发送到程序
   -如: LosslessZoom.exe "xx.png" "xx1.jpg" "xx2.bmp"
   -我测试过批处理(bat)，但是无法发送图片文件到程序

●高清化图片后保存于原图片目录
   -高清化的图片可以添加_后缀序号，保存于原图片目录

--------------------------------------------------------------

以上为我个人的建议。
本人习惯使用右键菜单调用各种程序以快速处理各类文件，因此希望作者添加上述功能

~~最后，^ ^ 这软件太厉害了
原以为平平无奇，谁承想惊为天人。高清化比 waifu2x caffe 还要厉害，果然 技术还是越新越牛啊
希望越来越好

**Comment by Karanoyo** [comment]
> 很好的建议, 后续会加上这两个功能.

期待。bye

**Comment by X-Lucifer** [comment]
添加任务时, 批量添加图片即可.
